//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_projesi.Models.varlik
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kategori()
        {
            this.tbl_urun = new HashSet<tbl_urun>();
        }
    
        public short KATEGORIID { get; set; }


        //Programa Bunun gerekli bir deðer olduðunu söyledik. Yani Boþ geçilemez...
        [Required(ErrorMessage = "Lütfen boþ býrakmayýnýz...")]
        public string KATEGORIAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_urun> tbl_urun { get; set; }
    }
}
